import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import LayoutMenu from '@/components/layout-menu/layout-menu'
import { AbsenceProvider } from '@/context/absence-context'
import { ToastProvider } from '@/features/toats-provider/toas-provider'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AbsenceProvider>
          <ToastProvider />
          <LayoutMenu>{children}</LayoutMenu>
        </AbsenceProvider>
      </body>
    </html>
  )
}
